name: Deploy Storybook

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: sterlingwes/gh-pages-deploy-action@v1.1
        with:
          # This needs to be added in the repo-level settings, under secrets; this value should be one of the write level access tokens for our organization.
          access-token: ${{ secrets.ACCESS_TOKEN }}
          source-directory: docs
          build-command: npm build-sb
